version: "3"
services:
  db:
    image: jaspeen/oracle-xe-11g
    container_name: oracle-xe-18c
    restart: unless-stopped
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      - ORACLE_PWD=1234
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: