spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:oracle:thin:@www.trito.co.kr:1521:TRITODB
    username: home_dev
    password: trito114
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        show_sql: ture
        format_sql: true

  flyway:
    baseline-on-migrate: true   # 기존데이터에 마이그레이션
    out-of-order: true          # 버전 순서와 상관없이 마이그레이션
    baseline-version: 1         # 기준 버전

logging:
  level:
    org.hibernate:
      sql: debug