spring:
  config:
    activate:
      on-profile: dev
  jwt:
    secret: 4b5c0b4bfa644e81161457bc9a5dae3f8ed9c0050ba8610d99f46c9e59845b6f
  datasource:
    url: jdbc:oracle:thin:@www.trito.co.kr:1521:TRITODB
    username: trito_dev
    password: trito114
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none #해당 속성값이 create 인 경우 jqa에 포함되어있는 테이블을 삭제 후 재생성함.

    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate:
      sql: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: kr.co.trito.domain.repository.mybatis

