CREATE TABLE TBSY_USER_INFO (
    USER_ID VARCHAR2(30 BYTE) NOT NULL,
    PASSWD VARCHAR2(100 BYTE) NOT NULL,
    USER_NM VARCHAR2(20 BYTE) NOT NULL,
    SAWON_NO VARCHAR2(7 BYTE),
    USE_YN VARCHAR2(1 BYTE),
    REG_DATE DATE,
    UPT_DATE DATE,
    REG_ID VARCHAR2(30 BYTE),
    UPT_ID VARCHAR2(30 BYTE),
    PRIMARY KEY (USER_ID)
);

CREATE TABLE TBSY_SAWON_INFO (
    SAWON_NO VARCHAR2(7 BYTE) NOT NULL,
    SAWON_GBN VARCHAR2(10 BYTE) NOT NULL,
    SAWON_NM VARCHAR2(20 BYTE) NOT NULL,
    DEPT_CD VARCHAR2(10 BYTE),
    JIKGYUB VARCHAR2(10 BYTE) NOT NULL,
    JIKCHECK VARCHAR2(50 BYTE),
    IN_DATE VARCHAR2(8 BYTE) NOT NULL,
    OT_DATE VARCHAR2(8 BYTE),
    BT_DATE VARCHAR2(8 BYTE),
    SEX_GB VARCHAR2(1 BYTE) NOT NULL,
    HP_TEL VARCHAR2(20 BYTE),
    TEL_NO VARCHAR2(20 BYTE),
    POST_NO VARCHAR2(6 BYTE),
    ADDR1 VARCHAR2(200 BYTE),
    ADDR2 VARCHAR2(1 BYTE),
    TEAM_YN VARCHAR2(1 BYTE),
    REG_DATE DATE,
    UPT_DATE DATE,
    REG_ID VARCHAR2(30 BYTE),
    UPT_ID VARCHAR2(30 BYTE),
    PRIMARY KEY(SAWON_NO)
);

CREATE TABLE TBSY_DEPT (
    DEPT_CD VARCHAR2(10 BYTE) NOT NULL,
    START_DT VARCHAR2(8 BYTE) NOT NULL,
    END_DT VARCHAR2(8 BYTE) NOT NULL,
    DEPT_NM VARCHAR2(100 BYTE) NOT NULL,
    LEV NUMBER(5) NOT NULL,
    UP_DEPT_CD VARCHAR2 (10 BYTE) NOT NULL,
    DEPT_YN VARCHAR2 (1 BYTE),
    SORT_SEQ NUMBER (10),
    REG_DT DATE,
    UPT_DT DATE,
    YAKEO_NM VARCHAR2 (50 BYTE),
    REG_ID VARCHAR2 (30 BYTE),
    UPT_ID VARCHAR2 (30 BYTE)
);